# Generated by Django 4.1.7 on 2023-03-18 16:27

from django.db import migrations, models
import ebbinghaus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='单词')),
                ('meaning', models.CharField(max_length=512, verbose_name='词义')),
                ('init_date', models.DateField(auto_now_add=True, verbose_name='初次学习单词时间')),
                ('next_date', models.DateField(verbose_name='下次学习单词时间')),
                ('review_times', models.CharField(max_length=256, validators=[ebbinghaus.models.validate_bool_list], verbose_name='复习时间列表')),
            ],
            options={
                'verbose_name': 'learn_words',
            },
        ),
    ]
