# Generated by Django 4.2.1 on 2023-05-17 17:11

from django.db import migrations, models
import ebbinghaus.models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=128, verbose_name='单词')),
                ('meaning', models.CharField(max_length=512, verbose_name='词义')),
                ('init_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='初次学习单词时间')),
                ('last_review', models.DateField(blank=True, null=True, verbose_name='上次复习时间')),
                ('next_date', models.DateField(db_index=True, verbose_name='下次学习单词时间')),
                ('review_times', models.CharField(max_length=256, validators=[ebbinghaus.models.validate_bool_list], verbose_name='复习时间列表')),
            ],
            options={
                'verbose_name': 'learn_word',
            },
        ),
        migrations.CreateModel(
            name='TodayArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('init_date', models.DateField(auto_now_add=True, verbose_name='生成日期')),
                ('last_review', models.DateField(verbose_name='上次复习日期')),
            ],
            options={
                'verbose_name': 'today_article',
            },
        ),
    ]
