# Generated by Django 4.2.1 on 2023-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbinghaus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='生成日期')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('last_review', models.DateField(verbose_name='上次复习日期')),
            ],
            options={
                'verbose_name': 'today_article',
            },
        ),
    ]
