# Generated by Django 4.2.1 on 2023-05-11 13:05

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebbinghaus', '0002_todayarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnwords',
            options={'verbose_name': 'learn_word'},
        ),
        migrations.AddField(
            model_name='learnwords',
            name='last_review',
            field=models.DateField(blank=True, null=True, verbose_name='上次复习时间'),
        ),
        migrations.AlterField(
            model_name='todayarticle',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
