# Generated by Django 4.2.1 on 2023-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebbinghaus', '0003_alter_learnwords_options_learnwords_last_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayarticle',
            name='init_date',
            field=models.DateField(auto_now_add=True, verbose_name='生成日期'),
        ),
    ]
